version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    tmpfs: "/datalog"
    ports:
      - "2181:2181"
    volumes:
      - <your-directory>:/var/lib/zookeeper/data
      - <your-directory>:/var/lib/zookeeper/log
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    volumes:
      - <your-directory>:/bitnami/kafka/data
    depends_on:
      - zookeeper
    networks:
      - my-network

  consumer:
    container_name: springboot_consumer
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    build:
      context: consumer
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    environment:
      - KAFKA-HOST=kafka
      - KAFKA-PORT=9092
      - DATABASE-URL=dburl
      - DATABASE-PORT=5432
      - DATABASE-NAME=kafka_test
      - DATABASE-SCHEMA=kafka_test
      - DATABASE-USERNAME=username
      - DATABASE-PASSWORD=password
    networks:
      - my-network

  producer:
    container_name: springboot_producer
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    build:
      context: producer
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - kafka
      - consumer
    ports:
      - "8081:8081"
    environment:
      - KAFKA-HOST=kafka
      - KAFKA-PORT=9092
      - CONSUMER-URL=consumer
      - CONSUMER-PORT=8082
    networks:
      - my-network

networks:
  my-network:
