spring:
  application:
    name: producer
  kafka:
    template:
      default-topic: order
    bootstrap-servers: ${KAFKA-HOST:localhost}:${KAFKA-PORT:9092}
    producer:
      bootstrap-servers: ${KAFKA-HOST:localhost}:${KAFKA-PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
server:
  port: 8081

api:
  consumer-url: http://${CONSUMER-URL:localhost}:${CONSUMER-PORT:8082}